name: '"Build dotenv from SSM" Action For GitHub Actions'
description: 'Build dotenv from AWS SSM based on template'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  environment:
    description: 'Environment name'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
